// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartEstimate.Infrastructure.Persistence;

#nullable disable

namespace SmartEstimate.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SmartEstimateDbContext))]
    partial class SmartEstimateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartEstimate.Domain.Estimates.Estimate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GrandTotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("GrandTotal");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("EstimateNumber");

                    b.Property<string>("ObjectAddress")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal?>("TotalArea")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalLaborAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("TotalLabor");

                    b.Property<decimal>("TotalMaterialsAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("TotalMaterials");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Estimates_CreatedAt");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("IX_Estimates_EstimateNumber_Active")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("Estimates", (string)null);
                });

            modelBuilder.Entity("SmartEstimate.Domain.Estimates.EstimateMaterialItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EstimateId")
                        .HasColumnType("uuid");

                    b.Property<string>("KnowledgeItemId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("MeasurementUnit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EstimateId")
                        .HasDatabaseName("IX_EstimateMaterialItems_EstimateId");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("IX_EstimateMaterialItems_ZoneId");

                    b.ToTable("EstimateMaterialItems", (string)null);
                });

            modelBuilder.Entity("SmartEstimate.Domain.Estimates.EstimateWorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EstimateId")
                        .HasColumnType("uuid");

                    b.Property<string>("KnowledgeItemId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("MeasurementUnit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EstimateId")
                        .HasDatabaseName("IX_EstimateWorkItems_EstimateId");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("IX_EstimateWorkItems_ZoneId");

                    b.ToTable("EstimateWorkItems", (string)null);
                });

            modelBuilder.Entity("SmartEstimate.Domain.Estimates.EstimateZone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EstimateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EstimateId")
                        .HasDatabaseName("IX_EstimateZones_EstimateId");

                    b.HasIndex("EstimateId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_EstimateZones_EstimateId_Name");

                    b.ToTable("EstimateZones", (string)null);
                });

            modelBuilder.Entity("SmartEstimate.Domain.Knowledge.ConstructionWork", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Status");

                    b.HasIndex("UnitId");

                    b.ToTable("ConstructionWorks", (string)null);
                });

            modelBuilder.Entity("SmartEstimate.Domain.Knowledge.KnowledgeCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("Status");

                    b.ToTable("KnowledgeCategories", (string)null);
                });

            modelBuilder.Entity("SmartEstimate.Domain.Knowledge.KnowledgeMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Status");

                    b.HasIndex("UnitId");

                    b.ToTable("KnowledgeMaterials", (string)null);
                });

            modelBuilder.Entity("SmartEstimate.Domain.Knowledge.MeasurementUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("MeasurementUnits", (string)null);
                });

            modelBuilder.Entity("SmartEstimate.Domain.Estimates.EstimateMaterialItem", b =>
                {
                    b.HasOne("SmartEstimate.Domain.Estimates.Estimate", null)
                        .WithMany("MaterialItems")
                        .HasForeignKey("EstimateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEstimate.Domain.Estimates.EstimateZone", null)
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SmartEstimate.Domain.Estimates.ValueObjects.Money", "UnitPrice", b1 =>
                        {
                            b1.Property<Guid>("EstimateMaterialItemId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("UnitPrice");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .IsUnicode(false)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("EstimateMaterialItemId");

                            b1.ToTable("EstimateMaterialItems");

                            b1.WithOwner()
                                .HasForeignKey("EstimateMaterialItemId");
                        });

                    b.Navigation("UnitPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartEstimate.Domain.Estimates.EstimateWorkItem", b =>
                {
                    b.HasOne("SmartEstimate.Domain.Estimates.Estimate", null)
                        .WithMany("WorkItems")
                        .HasForeignKey("EstimateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEstimate.Domain.Estimates.EstimateZone", null)
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SmartEstimate.Domain.Estimates.ValueObjects.Money", "UnitPrice", b1 =>
                        {
                            b1.Property<Guid>("EstimateWorkItemId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("UnitPrice");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .IsUnicode(false)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("EstimateWorkItemId");

                            b1.ToTable("EstimateWorkItems");

                            b1.WithOwner()
                                .HasForeignKey("EstimateWorkItemId");
                        });

                    b.Navigation("UnitPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartEstimate.Domain.Estimates.EstimateZone", b =>
                {
                    b.HasOne("SmartEstimate.Domain.Estimates.Estimate", null)
                        .WithMany("Zones")
                        .HasForeignKey("EstimateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartEstimate.Domain.Knowledge.ConstructionWork", b =>
                {
                    b.HasOne("SmartEstimate.Domain.Knowledge.KnowledgeCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartEstimate.Domain.Knowledge.MeasurementUnit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("SmartEstimate.Domain.Knowledge.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<Guid>("ConstructionWorkId")
                                .HasColumnType("uuid");

                            b1.Property<string>("De")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("NameDe");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("NameEn");

                            b1.Property<string>("Uk")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("NameUk");

                            b1.HasKey("ConstructionWorkId");

                            b1.HasIndex("Uk")
                                .IsUnique();

                            b1.ToTable("ConstructionWorks");

                            b1.WithOwner()
                                .HasForeignKey("ConstructionWorkId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartEstimate.Domain.Knowledge.KnowledgeCategory", b =>
                {
                    b.HasOne("SmartEstimate.Domain.Knowledge.KnowledgeCategory", null)
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("SmartEstimate.Domain.Knowledge.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<Guid>("KnowledgeCategoryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("De")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("NameDe");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("NameEn");

                            b1.Property<string>("Uk")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("NameUk");

                            b1.HasKey("KnowledgeCategoryId");

                            b1.HasIndex("Uk")
                                .IsUnique();

                            b1.ToTable("KnowledgeCategories");

                            b1.WithOwner()
                                .HasForeignKey("KnowledgeCategoryId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartEstimate.Domain.Knowledge.KnowledgeMaterial", b =>
                {
                    b.HasOne("SmartEstimate.Domain.Knowledge.KnowledgeCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartEstimate.Domain.Knowledge.MeasurementUnit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("SmartEstimate.Domain.Knowledge.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<Guid>("KnowledgeMaterialId")
                                .HasColumnType("uuid");

                            b1.Property<string>("De")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("NameDe");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("NameEn");

                            b1.Property<string>("Uk")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("NameUk");

                            b1.HasKey("KnowledgeMaterialId");

                            b1.HasIndex("Uk")
                                .IsUnique();

                            b1.ToTable("KnowledgeMaterials");

                            b1.WithOwner()
                                .HasForeignKey("KnowledgeMaterialId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartEstimate.Domain.Knowledge.MeasurementUnit", b =>
                {
                    b.OwnsOne("SmartEstimate.Domain.Knowledge.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<Guid>("MeasurementUnitId")
                                .HasColumnType("uuid");

                            b1.Property<string>("De")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("NameDe");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("NameEn");

                            b1.Property<string>("Uk")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("NameUk");

                            b1.HasKey("MeasurementUnitId");

                            b1.HasIndex("Uk")
                                .IsUnique();

                            b1.ToTable("MeasurementUnits");

                            b1.WithOwner()
                                .HasForeignKey("MeasurementUnitId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartEstimate.Domain.Estimates.Estimate", b =>
                {
                    b.Navigation("MaterialItems");

                    b.Navigation("WorkItems");

                    b.Navigation("Zones");
                });
#pragma warning restore 612, 618
        }
    }
}
